CREATE TABLE table_name (
	field_1 INT(10) UNSIGNED AUTO_INCREMENT NOT NULL,
	field_2 VARCHAR(20),
	field_3 DATETIME,
	field_4 TIMESTAMP,
	field_5 TEXT,
	field_6 BLOB,
	PRIMARY KEY (field_1)
)
[TYPE= {MYISAM | INNODB}]